# Generated by Django 4.0.7 on 2022-08-12 14:20

from django.db import migrations, models
import store.validator


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[store.validator.file_size_validator]),
        ),
    ]
